### ISSUE TITLE
sugarcane soil.profile error

### ISSUE THREAD

**Issue by daSilva5** [femiguez/apsimx#181]
Hi,
Sugarcane model is throwing an error while trying to edit the soil profile.

Capellano1275 <- get_isric_soil_profile(lonlat = c(148.11336,-23.2321))
ex_dir <- auto_detect_apsimx_examples()
edit_apsimx_replace_soil_profile("Sugarcane.apsimx",
                                 soil.profile = Capellano1275,
                                 src.dir = ex_dir,
                                 overwrite = TRUE)

Error in soil.node0[wsiswn][[1]] : subscript out of bounds

In the desktop the soil profiles need to have the var sugarcanesoil changed to "SugarcaneSoil". I think the problem is the same. these soil files might need editing to change some var name to work with the sugarcane model. If I run with the Wheat.apsimx it replaces the soil profile without problems.
Any idea of how to deal with that in R?

Thanks

**Comment by daSilva5** [comment]
Hi,
To maybe circumvent the error above I have also tried to create a soil using apsoil and read it with the read_apsim_soils() function. Which I also get an error. Is there another way of doing your own soil profile for using in R with apmix?

Ferrotry<-read_apsim_soils("ferrosoltry.soils",ex_dir)
edit_apsimx_replace_soil_profile("Sugarcane.apsimx",
                                 soil.profile = Ferrotry,
                                 src.dir = ex_dir,
                                 overwrite = TRUE)

Error: Object soil.profile should be of class 'soil_profile'
                      
[ferrosoltry.zip](https://github.com/user-attachments/files/17594968/ferrosoltry.zip)
           overwrite = TRUE)


Thanks

**Comment by femiguez** [comment]
@daSilva5 The Sugarcane example needs to be open through APSIM at least once, so that a number of things are fixed. One of these is the Initial Water. After this, I can edit the soil and run the example. See attached
[Sugarcane_soils.zip](https://github.com/user-attachments/files/17598987/Sugarcane_soils.zip)

Thanks for your interest in the package and let me know if you have any questions

**Comment by daSilva5** [comment]
> @daSilva5 The Sugarcane example needs to be open through APSIM at least once, so that a number of things are fixed. One of these is the Initial Water. After this, I can edit the soil and run the example. See attached [Sugarcane_soils.zip](https://github.com/user-attachments/files/17598987/Sugarcane_soils.zip)
> 
> Thanks for your interest in the package and let me know if you have any questions

Hi,
Thank you for your time and for the package!
Your simulation does not run for me. 
I just did one edit in the name of the simulation Sugarcane_example.apsimx to Sugarcane_famiguez.apsimx, all the rest the same.

```
sim0 <- apsimx("Sugarcane_famiguez.apsimx")
```
I get the following errors:

```
System.Exception: Error in file:.\Sugarcane_famiguez.apsimx
 ---> System.Exception: Error reading file .\Sugarcane_famiguez.apsimx
 ---> System.Exception: Unable to open file '.\Sugarcane_famiguez.apsimx'. File version is greater than the latest file version. Has this file been opened in a more recent version of Apsim?
   at Models.Core.ApsimFile.Converter.DoConvert(String st, Int32 toVersion, String fileName) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\ApsimFile\Converter.cs:line 72
   at Models.Core.ApsimFile.FileFormat.ReadFromString[T](String st, Action`1 errorHandler, Boolean initInBackground, String fileName) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\ApsimFile\FileFormat.cs:line 90
   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, Action`1 errorHandler, Boolean initInBackground) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\ApsimFile\FileFormat.cs:line 62
   --- End of inner exception stack trace ---
   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, Action`1 errorHandler, Boolean initInBackground) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\ApsimFile\FileFormat.cs:line 78
   at Models.Core.Run.SimulationGroup.Initialise() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationGroup.cs:line 219
   --- End of inner exception stack trace ---
ERRORS FOUND!!
```

Then I try to run a simulation that I have added a sugar soil in APSIMx desktop. And I get different errors depending on how I load the soil.
[SugarcaneFerrosoil.zip](https://github.com/user-attachments/files/17612974/SugarcaneFerrosoil.zip)

This part runs perfectly:
```
simfe0<-apsimx("SugarcaneFerrosoil.apsimx",src.dir = ex_dir)
inspect_apsimx("SugarcaneFerrosoil.apsimx", src.dir = ex_dir, 
               node = "Soil", 
               soil.child = "Water")

```

Then load soil:

```
Capellano1275 <- get_isric_soil_profile(lonlat = c(148.11336,-23.2321)fix=TRUE,
                              xargs = list(crops = "Sugarcane")

edit_apsimx_replace_soil_profile("SugarcaneFerrosoil.apsimx",
                                 soil.profile = Capellano1275,
                                 src.dir = ex_dir,
                                 #overwrite = TRUE,
                                 edit.tag = "_capellano")
sim1 <- apsimx("SugarcaneFerrosoil_capellano.apsimx",
               src.dir = ex_dir)
```
I get the following errors:

```
ERROR in file: C:\Users\....\AppData\Local\Programs\APSIM2024.8.7568.0\Examples\SugarcaneFerrosoil_capellano.apsimx
Simulation name: Simulation
Models.Core.SimulationException
 ---> System.Exception: SugarcaneSoil LL of 0.330 in layer 2 is above drained upper limit of 0.306
SugarcaneSoil LL of 0.340 in layer 5 is above drained upper limit of 0.320

   at Models.Soils.Soil.Check(ISummary summary) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Soils\Soil.cs:line 310
   at Models.Soils.Soil.OnDoInitialSummary(Object sender, EventArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Soils\Soil.cs:line 125
   at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Clock.cs:line 315
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 295
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 304
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 136
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 226
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 189
ERRORS FOUND!!
```
Then I try to load the soil as I was doing before:

```
Capellano1275 <- get_isric_soil_profile(lonlat = c(148.11336,-23.2321))

edit_apsimx_replace_soil_profile("SugarcaneFerrosoil.apsimx",
                                 soil.profile = Capellano1275,
                                 src.dir = ex_dir,
                                 #overwrite = TRUE,
                                 edit.tag = "_capellano2")

sim1 <- apsimx("SugarcaneFerrosoil_capellano2.apsimx",
               src.dir = ex_dir)
```
Then I get the following errors:

````
ERROR in file: C:\Users\.....\AppData\Local\Programs\APSIM2024.8.7568.0\Examples\SugarcaneFerrosoil_capellano2.apsimx
Simulation name: Simulation
Models.Core.SimulationException
 ---> System.Exception: Cannot find a soil crop parameterisation called SugarcaneSoil
   at Models.Sugarcane.sugar_read_root_params() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Sugarcane\Sugarcane.cs:line 13249
   at Models.Sugarcane.sugar_start_crop(Double plants, Int32 Ratoon, Double sowing_depth, String Cultivar) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Sugarcane\Sugarcane.cs:line 13145
   at Models.Sugarcane.SowNewPlant(Double PlantingDensity, Double Depth, String CultivarName) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Sugarcane\Sugarcane.cs:line 13859
   at Models.ScriptSimulationsSimulationFieldManagerfolderSUGARmanagement.OnStartOfDay(Object sender, EventArgs e)
   at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Clock.cs:line 347
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 295
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 304
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 136
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 226
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 189
ERRORS FOUND!!

```

**Comment by femiguez** [comment]
@daSilva5 Where you able to get this to work?

**Comment by daSilva5** [comment]
> @daSilva5 Where you able to get this to work?
Hi,
First thank you for your reply, and for the package. I had some version warning and decided to update APSIM, but then it causes problems with firewall. 
I decided not to add the path to ApsimNG.exe and it seems to work. 
Your example seems to be working. But then when I try to replicate it using the Sugarcane.apsimx example it does not. 
ex_dir is just the path to the simulation file.
```
inspect_apsimx("Sugarcane.apsimx", src.dir = ex_dir, 
+                node = "Soil", 
+                soil.child = "Water")
Soil Type:  
Latitude:  0 
Longitude:  0 
Soil children: Initial water Physical SoilWater Organic Chemical Temperature Nutrient Initial conditions 
Error in inspect_apsimx("Sugarcane.apsimx", src.dir = ex_dir, node = "Soil",  : 
  soil.child likely not present
> sim0<-apsimx("Sugarcane.apsimx",src.dir = ex_dir)
> Capellano1275 <- get_isric_soil_profile(lonlat = c(148.11336,-23.2321), fix = TRUE,                          xargs = list(crops = "Sugarcane"))
InitialWater cannot be greater than DUL in layer: 1 .
 It was adjusted to the value of 0.2808 .
InitialWater cannot be greater than DUL in layer: 2 .
 It was adjusted to the value of 0.2754 .
InitialWater cannot be greater than DUL in layer: 3 .
 It was adjusted to the value of 0.279 .
InitialWater cannot be greater than DUL in layer: 4 .
 It was adjusted to the value of 0.2925 .
InitialWater cannot be greater than DUL in layer: 5 .
 It was adjusted to the value of 0.288 .
InitialWater cannot be greater than DUL in layer: 6 .
 It was adjusted to the value of 0.2907 .
> edit_apsimx_replace_soil_profile("Sugarcane.apsimx",
+                                  soil.profile = Capellano1275,
+                                  src.dir = ex_dir,
+                                  #overwrite = TRUE,
+                                  edit.tag = "_capellano2")
Error in soil.node0[wsiswn][[1]] : subscript out of bounds
```

If I run with an example that I have added a Sugarsoil and edited the soil name manually in the desktop application. 

[SugarcaneFerrosoil.zip](https://github.com/user-attachments/files/17624523/SugarcaneFerrosoil.zip)

```
simfe0<-apsimx("SugarcaneFerrosoil.apsimx",src.dir = ex_dir)
> Capellano1275 <- get_isric_soil_profile(lonlat = c(148.11336,-23.2321), fix = TRUE, xargs = list(crops = "Sugarcane"))
InitialWater cannot be greater than DUL in layer: 1 .
 It was adjusted to the value of 0.2808 .
InitialWater cannot be greater than DUL in layer: 2 .
 It was adjusted to the value of 0.2754 .
InitialWater cannot be greater than DUL in layer: 3 .
 It was adjusted to the value of 0.279 .
InitialWater cannot be greater than DUL in layer: 4 .
 It was adjusted to the value of 0.2925 .
InitialWater cannot be greater than DUL in layer: 5 .
 It was adjusted to the value of 0.288 .
InitialWater cannot be greater than DUL in layer: 6 .
 It was adjusted to the value of 0.2907 .
> edit_apsimx_replace_soil_profile("SugarcaneFerrosoil.apsimx",
+                                  soil.profile = Capellano1275,
+                                  src.dir = ex_dir,
+                                  #overwrite = TRUE,
+                                  edit.tag = "_capellano2")
Created:  C:\Users\......\AppData\Local\Programs\APSIM2024.11.7609.0\Examples/SugarcaneFerrosoil_capellano2.apsimx 
> sim1 <- apsimx("SugarcaneFerrosoil_capellano2.apsimx",
+                src.dir = ex_dir)
----------------------------------------------
ERROR in file: C:\Users\.....\AppData\Local\Programs\APSIM2024.11.7609.0\Examples\SugarcaneFerrosoil_capellano2.apsimx
Simulation name: Simulation
Models.Core.SimulationException
 ---> System.Exception: SugarcaneSoil LL of 0.330 in layer 2 is above drained upper limit of 0.306
SugarcaneSoil LL of 0.340 in layer 5 is above drained upper limit of 0.320

   at Models.Soils.Soil.Check(ISummary summary) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Soils\Soil.cs:line 281
   at Models.Soils.Soil.OnDoInitialSummary(Object sender, EventArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Soils\Soil.cs:line 123
   at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Clock.cs:line 310
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 297
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 306
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 136
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 226
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 189
ERRORS FOUND!!
Error in read_apsimx(file = sub("apsimx$", "db", file), src.dir = src.dir,  : 
  No report tables found
In addition: Warning message:
In shell(cmd = run.strng, translate = TRUE, intern = intern) :
  'C:/PROGRA~1/APSIM2024.11.7609.0/bin/Models.exe C:\Users\.....\AppData\Local\Programs\APSIM2024.11.7609.0\Examples/SugarcaneFerrosoil_capellano2.apsimx' execution failed with error code 1

```

Did you change anything in the code of you .apsimx ?


Kind regards,
Isis

**Comment by femiguez** [comment]
@daSilva5 According to the last error message, the soil is not properly constructed ("LL is greater than DUL"). I don't know why. This code works for me.

```r
Capellano1275 <- get_isric_soil_profile(lonlat = c(148.11336,-23.2321), fix = TRUE, xargs = list(crops = "Sugarcane"))

check_apsimx_soil_profile(Capellano1275)
plot(Capellano1275, property = "water")
plot(Capellano1275, property = "initialwater")
plot(Capellano1275, property = "texture")

edit_apsimx_replace_soil_profile("Sugarcane_example.apsimx",
                                 soil.profile = Capellano1275,
                                 edit.tag = "_capellano")

sim2 <- apsimx("Sugarcane_example_capellano.apsimx")
```

**Comment by daSilva5** [comment]
> @daSilva5 According to the last error message, the soil is not properly constructed ("LL is greater than DUL"). I don't know why. This code works for me.
> 
> ```r
> Capellano1275 <- get_isric_soil_profile(lonlat = c(148.11336,-23.2321), fix = TRUE, xargs = list(crops = "Sugarcane"))
> 
> check_apsimx_soil_profile(Capellano1275)
> plot(Capellano1275, property = "water")
> plot(Capellano1275, property = "initialwater")
> plot(Capellano1275, property = "texture")
> 
> edit_apsimx_replace_soil_profile("Sugarcane_example.apsimx",
>                                  soil.profile = Capellano1275,
>                                  edit.tag = "_capellano")
> 
> sim2 <- apsimx("Sugarcane_example_capellano.apsimx")
> ```

Hi,
After deleting the old APSM version I had and repeating it a lot of times, it is now working with different simulations that I have!!!!
 I hope it continue to work from now on!


Thank you for your help

**Comment by femiguez** [comment]
Closing this. Feel free to open a new issue.
